# -*- coding: utf-8 -*-
"""Ivan_Tobar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QYzXfh8iAmVRDQ8HsoMJPu6S7zd-CMX9
"""

#Almacenamiento dato de personas
registros = {}

def verificar_nif(nif):
    if len(nif) != 10:
        return False
    if not nif[:8].isdigit() or not nif[8:].isalpha():
        return False
    if nif[8:].islower() or (nif[9] != 'X' and not nif[9:].isupper()):
        return False
    return True

def grabar_nif():
    nif = input("Ingresa tu número de NIF: ")
    with open('nif.txt', 'w') as archivo:
        archivo.write(nif)

    print("NIF grabado exitosamente en el archivo.")

grabar_nif()
nif_generado = generar_nif()
print("NIF generado:", nif_generado)

nombre = input("Ingrese el nombre: ")
while len(nombre) < 8:
        print("El nombre debe tener al menos 8 caracteres. Vuelva a intentarlo.")
        nombre = input("Ingrese el nombre: ")

edad = int(input("Ingrese la edad: "))
while edad < 0:
  print("La edad debe ser mayor o igual a 0. Vuelva a intentarlo.")
  edad = int(input("Ingrese la edad: "))

  registros[nif] = {'nombre': nombre, 'edad': edad}
  print("Registro grabado con éxito.")

def buscar():
    nif = input("Ingrese el NIF de la persona a buscar: ")
    if nif in registros:
        persona = registros[nif]
        print("Información de la persona:")
        print(f"NIF: {nif}")
        print(f"Nombre: {persona['nombre']}")
        print(f"Edad: {persona['edad']}")
        if nif[:2] == '00':
            print("La persona NO pertenece a la Unión Europea.")
        else:
            print("La persona pertenece a la Unión Europea.")
    else:
        print("No se encontró ninguna persona con el NIF proporcionado.")

def imprimir_certificados():
    for nif, persona in registros.items():
        print("Certificados de la persona:")
        print(f"Certificado de nacimiento - NIF: {nif} - Nombre: {persona['nombre']}")
        print(f"Certificado de estado conyugal - NIF: {nif} - Nombre: {persona['nombre']}")
        if nif[:2] == '00':
            print(f"Certificado de pertenencia a la Unión Europea - NIF: {nif} - Nombre: {persona['nombre']}")

def menu():
    while True:
        print("\n--- Menú ---")
        print("1. Grabar")
        print("2. Buscar")
        print("3. Imprimir certificados")
        print("4. Salir")
        opcion = input("Seleccione una opción (1-4): ")

        if opcion == '1':
            grabar()
        elif opcion == '2':
            buscar()
        elif opcion == '3':
            imprimir_certificados()
        elif opcion == '4':
            print("¡Gracias por usar el programa!")
            print("Creado por [Tu nombre y apellido]")
            print("Versión 1.0")
            break
        else:
            print("Opción inválida. Vuelva a intentarlo.")

menu()